name: CI

on:
  pull_request:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: set yaml file
        uses: microsoft/variable-substitution@v1
        with:
          files: ./src/main/resources/application.yaml
        env:
          spring.datasource.url: ${{ secrets.MYSQL_URL }}
          spring.datasource.username: ${{ secrets.MYSQL_USERNAME }}
          spring.datasource.password: ${{ secrets.MYSQL_PASSWORD }}
          redis.host: ${{ secrets.REDIS_HOST }}
          redis.port: ${{ secrets.REDIS_PORT }}
          redis.password: ${{ secrets.REDIS_PASSWORD }}
          spring.jwt.access-secret: ${{ secrets.JWT_ACCESS_SECRET }}
          spring.jwt.refresh-secret: ${{ secrets.JWT_REFRESH_SECRET }}
          spring.jwt.access-expiration: ${{ secrets.JWT_ACCESS_EXPIRATION }}
          spring.jwt.refresh-expiration: ${{ secrets.JWT_REFRESH_EXPIRATION }}
          optimization-api.uri: ${{ secrets.OPTIMIZATION_API_URI }}
          kakao.api.key :  ${{ secrets.KAKAO_API_KEY }}
          server.url: ${{ secrets.SERVER_URL }}

      - name: Grant execute permission to gradlew
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew build -x test
        shell: bash

